<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
       <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
    <%@ taglib uri="/WEB-INF/tld/struts-html.tld" prefix="html"%>
    <%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
    <%@ taglib uri="/WEB-INF/tld/struts-logic.tld" prefix="logic"%>
    <%@ taglib uri="/WEB-INF/tld/struts-bean.tld" prefix="bean"%>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
    <%@ include file="/common/include.jsp"%> 
   <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
    
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employees Health Scheme</title>
<link href="css/themes/<%=themeColour%>/commonEhfCss.css" rel="stylesheet" type="text/css" media="screen">
<link href="css/themes/<%=themeColour%>/theme.css" rel="stylesheet" type="text/css" media="screen">

<script src="js/jquery-1.9.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css">
<%@ include file="/common/includeCalendar.jsp"%> 
<link href="css/select2.min.css" rel="stylesheet">
<title ><fmt:message key="EHF.Title.PatientRegistration"/></title>
<LINK href="css/patient.css" type="text/css" rel="stylesheet">

<script src="js/jquery.msgBox.js" type="text/javascript"></script>
<script src="js/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript" src="js/patientscripts.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="bootstrap/js/bootbox.min.js"></script>

<script src="js/select2.min.js"></script>
<link rel="stylesheet" href="css/jquery.ui.core.css">
<link rel="stylesheet" href="css/jquery.ui.datepicker.css">
<link rel="stylesheet" href="css/jquery.ui.theme.css">
<link rel="stylesheet" href="css/jquery-ui.css">
	<script src="js/jquery.ui.core.js"></script>
	<script src="js/jquery.ui.widget.js"></script>
	<script src="js/jquery.ui.datepicker.js"></script>
	<script src="js/DateTimePicker.js"></script>
	
<style>
.ui-menu .ui-menu-item {
        margin:0;
        padding: 0;
        width: 200px;
        list-style-type: none;
}
#otherDrugs th, #otherDrugs td {
  text-align: center;
  padding: 4px;
  border: 1px solid #cce7cc;
  white-space: nowrap;
}

#otherDrugs input[type="text"], 
#otherDrugs input[type="file"] {
  
  height: 22px;
  box-sizing: border-box;
}

#otherDrugs th {
  color: #007b33;
  font-weight: bold;
}
#teamDtlsTbl {
    table-layout: fixed;
    width: 100%;
}

#teamDtlsTbl th,
#teamDtlsTbl td {
    height: 45px;
    vertical-align: middle;
    padding: 6px 8px;
    overflow: hidden;
    text-overflow: ellipsis;
}

#teamDtlsTbl th:nth-child(7),
#teamDtlsTbl td:nth-child(7) {
    width: 250px;
    white-space: normal;
    word-break: break-word;
}
#otherDrugs {
  table-layout: fixed;
}
.drugExpiryDate {
    background: url("<%=request.getContextPath()%>/images/calend.gif") no-repeat right 8px center;
    background-size: 16px 16px;
    padding-right: 30px; /* space for icon */
    cursor: pointer;
}
.invoiceDate_ {
    background: url("<%=request.getContextPath()%>/images/calend.gif") no-repeat right 6px center;
    background-size: 16px 16px;
    padding-right: 28px;
    cursor: pointer;
}

#drugForm .select2-container {
    width: 100% !important;
}

</style>
</head>
<body>
<br/>
<form id="vendorForm" method="post" action="vendorActionNew.do" >
<table id="drugForm" width="100%" style="margin:0 auto; table-layout: fixed;">
<tr>
    <th class="tbheader" colspan="4" style="background-color: #38b376;">DRUG ISSUE FORM</th>
</tr>
<tr>
    <td width="18%" class="labelheading1 tbcellCss"><b>Wellness Center Name</b> <font color="red">*</font></td>
    <td width="22%" class="labelheading1 tbcellCss"><b>Status</b><font color="red">*</font></td>
    <td width="22%" class="labelheading1 tbcellCss"><b>PO </b><font color="red">*</font></td>
    <td width="38%" class="labelheading1 tbcellCss"><b>Drug List </b></td>
</tr>
<tr>
   <td width="18%" valign="top" class="tbcellBorder">
    <html:select property="dispname" name="patientForm" styleId="dispname"
                 title="Select Wellness Center"
                 onchange="onWcChange();" style="width: 100%;">
        <html:option value="-1">ALL WCs</html:option>
        <html:options collection="wclist" property="DISP_ID" labelProperty="DISP_NAME" />
    </html:select>
   </td>
   
   <td width="22%" valign="top" class="tbcellBorder">
    <html:select name="patientForm" property="status" styleId="status"
                 title="Select Status" onchange="onStatusChange();" style="width: 100%;">
        <html:option value="-1">Select</html:option>
        <html:option value="CD1416">PO's generated by WC</html:option>
        <html:option value="CD1420">Partially Submitted By Vendor</html:option>
    </html:select>
   </td>
   
   <td width="22%" valign="top" class="tbcellBorder">
     <select id="poDropdown" name="poDropdown" onchange="handlePoSelection()" style="width: 100%;">
       <option value="-1">Select</option>
     </select>
   </td>
   
   <td width="38%" valign="top" class="tbcellBorder">
    <select id="drugListDropdown" name="drugListDropdown" 
            onchange="handleDrugSelection()" style="width:100%;">
        <option value="-1">Select</option>
        <option value="ALL">Select All</option>
    </select>
   </td>
</tr>

</table>
<br/>
<br/>
  		<div id="phcCountDiv" style = "display:none;">
		<div style="width:100%; overflow-x:auto; overflow-y:auto; max-height:450px; border:1px solid #ccc;">
		<section id="no-more-tables">
          <table id="teamDtlsTbl" style = "width: 100%;font-size: 12px;" class="table fontclass table-bordered" >
					 <thead id="thead_dashboard" style = "background-color: #b4d6b4;">
					 	 <tr id="teamHeaderRow">
					 		<th class='tableHeader bothSideBorder2Px' style = "width: 30px;"><label><input type='checkbox' id='checkAll' class='selectableCheckbox' title='click here to select all Cases' onclick='fn_checkAll();' /></label></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 100px;text-align:center"><b>S.No</b></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 120px;text-align:center"><b>PO NO</b></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 130px;text-align:center"><b>PO DATE</b></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 200px;text-align:center"><b>BRAND NAME</b></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 100px;text-align:center"><b>DRUG TYPE</b></th> 
							<th class="tableHeader bothSideBorder2Px" style="width: 200px;text-align:center"><b>DRUG NAME</b></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 70px;text-align:center"><b>PO QTY</b></th> 
							 
							<th class="tableHeader bothSideBorder2Px" style="width: 180px;text-align:center"><b>RATE CONTRACT PRICE</b></th>
							<th class="tableHeader bothSideBorder2Px" style="width: 160px;text-align:center">Batch No <font color="red">*</font></th>
          					<th class="tableHeader bothSideBorder2Px" style="width: 130px;text-align:center">Invoice Date <font color="red">*</font></th>
					        <th class="tableHeader bothSideBorder2Px" style="width: 150px;text-align:center">Invoice Number <font color="red">*</font></th>
					        <th class="tableHeader bothSideBorder2Px" style="width: 130px;text-align:center">Expiry Date <font color="red">*</font></th>
					        <th id="quantityHeader" class="tableHeader bothSideBorder2Px" style="width: 120px;text-align:center">Quantity <font color="red">*</font></th>
					        <th id = "pendingQtyHeader" class="tableHeader bothSideBorder2Px" style="width: 120px;text-align:center">Pending Quantity <font color="red">*</font></th>
					        <th class="tableHeader bothSideBorder2Px" style="width: 120px;text-align:center">GST SLAB <font color="red">*</font></th>
					        <th class="tableHeader bothSideBorder2Px" style="width: 150px;text-align:center">PO Amount <font color="red">*</font></th>
					        <th class="tableHeader bothSideBorder2Px" style="width: 150px;text-align:center">GST Amount <font color="red">*</font></th>
					        <th class="tableHeader bothSideBorder2Px" style="width: 150px;text-align:center">Invoice Amount <font color="red">*</font></th>
					        
						</tr>
					</thead>
					<tbody id="tbodyC1">
	           </tbody>	
					
					</table>
					</section>
					</div>
					</div>
				<br/>
			<tr>
		<td align="center">
		<input class="but" type="button" value="Submit&Print" id="submitBtn" onclick="javascript:fn_submit();" style = "margin-left: 43%;display:none;background-color: green;"/></td>	
	 	</tr>
	 	<div id="processImagetable" style="top:10%;position:absolute;z-index:60;height:100%;display:none;">
    <table border="0" align="center" width="100%" style="height:400">
        <tr>
            <td>
                <div id="processImage" align="center">
                    <img src="images/Progress.gif" width="100" height="100" border="0"></img>
                </div>
            </td>
        </tr>
    </table>
</div>
<html:hidden name="patientForm" property="drugs" styleId="drugs"/>
<input type="hidden" id="drugList" value="<%= session.getAttribute("drugList") %>" />
<input type="hidden" id="hiddenStatus"/>
<input type="hidden" id="hiddenIndentNo"/>
<input type="hidden" id="hiddenItemIds">
<input type="hidden" id="hiddenItemId">
<input type="hidden" id="hiddenPoNo">
</form>
<script type="text/javascript">
var loadedDrugList=new Array();

var date = new Date();
var m = date.getMonth(), d = date.getDate(), y = date.getFullYear();
var GLOBAL_INVOICE_NO = "";
//var GLOBAL_INVOICE_DTE = "";

function fn_loadImage() {
    document.getElementById('processImagetable').style.display = "";
}

function fn_hideImage() {
    document.getElementById('processImagetable').style.display = "none";
}

 $(function() {

		$( "#invoiceDateMn" ).datepicker({
			defaultDate: "+1w",
			changeMonth: true,
			changeYear: true,
			showOn: "both", 
         buttonImage: "images/calend.gif", 
         buttonText: "Calendar",
         buttonImageOnly: true ,
           minDate: "-5Y",
			maxDate:  0,			
			onClose: function( selectedDate ) {
				$( "#toDate" ).datepicker( "option", "minDate", selectedDate );
			}
		});
 });
 
 $(document).on("input", ".drugExpiryDate, .invoiceDate_", function () {
	    this.value = this.value.replace(/[^0-9\-]/g, '');
	});

 
	function fn_checkBatchNo(num)
	  {
		  var batchNo=num.value;
		  if(batchNo!=null && batchNo!="")
			 {
			 var regAlphaNum=/^[0-9a-zA-Z,.:\/\- ]+$/;
			 if(batchNo.trim().search(regAlphaNum)==-1)
				 {
				 alert("Only alphanumerics and -,.,:,/ are allowed in Batch Number");
				 var bID=num.id;
				 document.getElementById(bID).value="";
				 document.getElementById(bID).focus();
				 return false;
				 }
			 num.value=batchNo.replace(/\s/g, '');;
			 }
	  }
	function resetStatus() {
	    document.getElementById("status").value = "-1";
	    
	}
	function getTodayDate() {
	    var d = new Date();
	    return String(d.getDate()).padStart(2, "0") + "-" +
	           String(d.getMonth() + 1).padStart(2, "0") + "-" +
	           d.getFullYear();
	}

	function resetDrugDropdown() {

	    var drugDropdown = $("#drugListDropdown");

	    if (drugDropdown.hasClass("select2-hidden-accessible")) {
	        drugDropdown.select2('destroy');
	    }

	    drugDropdown.empty();
	    drugDropdown.append("<option value='-1'>Select</option>");

	    drugDropdown.select2({
	        width: '100%',
	        placeholder: "Select",
	        allowClear: true
	    });
	}

	
	function resetPoAndTable() {

	    $("#poDropdown").val("-1");
	    $("#poDropdown").empty().append("<option value='-1'>Select</option>");
	  
	    resetDrugDropdown();

	    $("#tbodyC1").empty();
	    $("#teamDtlsTbl").hide();
	    $("#submitBtn").hide();
	    $("#phcCountDiv").hide();

	    $("#statusHidden").remove();
	}

	function onWcChange() {

	    $("#status").val("-1");

	    resetPoAndTable();
	}

	function onStatusChange() {

	    resetPoAndTable();

	    loadPoList();
	}

	function loadPoList() {
	    var wc = document.getElementById("dispname").value;
	    var status = document.getElementById("status").value;

	    var poDropdown = document.getElementById("poDropdown");
	    poDropdown.innerHTML = '<option value="-1">Select</option>';

	    if (wc === "-1") return;
	    if (status === "-1") return;

	    fetchPODropdown(wc, status);
	}

	function fn_checkDrugQuantity(quantity)
	  {
		  var drugQuantity=quantity.value;
		  if(drugQuantity!=null && drugQuantity!="")
			 {
			 var regAlphaNum=/^[0-9]+$/;
			 if(drugQuantity.trim().search(regAlphaNum)==-1)
				 {
				 alert("Only Numbers are allowed in Quantity.(No Decimal Points)");
				 var qID=quantity.id;
				 document.getElementById(qID).value="";
				 document.getElementById(qID).focus();
				 return false;
				 }
			 quantity.value=drugQuantity.replace(/\s/g, '');;
			 }
		  
	  }
	
	function fetchPODropdown(dispId) { 
		var status = document.getElementById("status").value; 
			if (dispId === "-1") { 
			document.getElementById("poDropdown").innerHTML = '<option value="-1">SELECT PO</option>'; 
			$("#submitBtn").hide();
			$("#tbodyC1").empty();
			return;
			} 
		var xhr = new XMLHttpRequest(); 
		xhr.open("POST", "vendorActionNew.do?actionFlag=getIndentedPoRpt1", true); 
		xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); 
		xhr.onreadystatechange = function () {
		    if (xhr.readyState === 4 && xhr.status === 200) {

		        var poDropdown = document.getElementById("poDropdown");
		        poDropdown.innerHTML = '<option value="-1">SELECT PO</option>';

		        try {
		            var response = JSON.parse(xhr.responseText); 
		            if (response.length === 0) {
		                var opt = document.createElement("option");
		                opt.value = "-1";
		                opt.text = "No POs found";
		                poDropdown.appendChild(opt);
		                return;
		            }

		            response.forEach(function (item) {
		                if (item.POID && item.POID !== "-NA-") {
		                    var opt = document.createElement("option");
		                    opt.value = item.POID;
		                    opt.text = item.POID;
		                    poDropdown.appendChild(opt);
		                }
		            });

		        } catch (e) {
		            console.error("JSON parse error:", e);
		            alert("Error loading PO list");
		        }
		    }
		};
 
		xhr.send("dispname=" + encodeURIComponent(dispId) + "&status=" + encodeURIComponent(status)); 
		}
	var minExpiryDate = null;
	function poRpt(poNo, status) {
	    $.ajax({
	        url: 'vendorActionNew.do?actionFlag=poNoOnclick1', 
	        type: 'POST',
	        data: { 'poNo': poNo, 'status': status },
	        success: function(data) {
	            data = data.replace("*", "");
	            var result = JSON.parse(data);

	            var drugDropdown = $("#drugListDropdown");
	            drugDropdown.empty();
	            drugDropdown.append("<option value='ALL'>--SELECT ALL--</option>");

	            for (var i = 0; i < result.length; i++) {
	                var drugOption = "<option value='" + result[i].DRUG_ID + "'>" + result[i].DRUGNAME + "</option>";
	                drugDropdown.append(drugOption);
	            }
	            
	            if (drugDropdown.hasClass("select2-hidden-accessible")) {
	                drugDropdown.select2('destroy');
	            }

	            drugDropdown.select2({
	                width: '100%',
	                placeholder: "Select",
	                allowClear: true
	            });
	            fn_hideImage();
	           // $("#drugListDropdown").show();
	        }
	    });
	}
	
	function handleDrugSelection() {
		var poNo = document.getElementById("poDropdown").value;
		var status = document.getElementById("status").value; 
	    var drugId = $("#drugListDropdown").val();
	    
	    if (drugId === "-1") {
	        return; 
	    }
	    
	    if (drugId === "ALL") {
	        poRpt1(poNo, status, "");
	    } else {
	        poRpt1(poNo, status, drugId);
	    }

	    $("#teamDtlsTbl").hide();
	    $("#submitBtn").hide();
	    $("#tbodyC1").empty();
	    
	    fn_loadImage();
		
	    poRpt1(poNo, status,drugId);
	}
	
	function poRpt1(poNo, status,drugId) {
		GLOBAL_INVOICE_NO = "";
	    $(".invoiceNumber").val("");
	    $("#checkAll").prop("checked", false);
	    
	    //$("#drugListDropdown").select2().val('');
	    
	    $.ajax({
	        url: 'vendorActionNew.do?actionFlag=poNoOnclick1',
	        type: 'POST',
	        data: { 'poNo': poNo, 'status': status,'drugId' : drugId },
	        success: function(data) {
	            data = data.replace("*", "");
	            var result = JSON.parse(data);
	            var content = "";
	            GLOBAL_INVOICE_NO = "";
	            $(".invoiceNumber").val("");
	            $("#checkAll").prop("checked", false);
	            
	        	if (status === 'CD1420') {
	        		$("#quantityHeader").html("Issued Quantity <font color='red'>*</font>");
            	    $("#pendingQtyHeader").show();
            	} else {
            		$("#quantityHeader").html("Quantity <font color='red'>*</font>");
            	    $("#pendingQtyHeader").hide();
            	}

	            if (result.length === 0) {
	            
	                document.getElementById("tbodyC1").innerHTML = 
	                    "<tr><td colspan='11' style='text-align:center;color:red;'>No data available</td></tr>";
	                return;
	            }
	            var today = new Date();
	            var todayStr =
	                String(today.getDate()).padStart(2, "0") + "-" +
	                String(today.getMonth() + 1).padStart(2, "0") + "-" +
	                today.getFullYear();

	            for (var j = 0; j < result.length; j++) {
	            	
	                content += "<tr>";
	                content += "<td><label><input type='checkbox' class='selectableCheckbox'></label></td>";
	                content += "<td style='text-align:center;font-size:13px;'>" + (j + 1) + "</td>";
	                content += "<td style='cursor:pointer;text-align:center'>" + result[j].POID + "</td>";
	                var poDateOnly = "";

	                if (result[j].PODATE) {
	                    var dateStr = result[j].PODATE.toString();
	                    var d;

	                    if (dateStr.match(/^\d{4}-\d{2}-\d{2}/)) {
	                        var parts = dateStr.substring(0, 10).split("-");
	                        poDateOnly = parts[2] + "-" + parts[1] + "-" + parts[0];
	                    } 
	                   
	                    else {
	                        d = new Date(dateStr);
	                        poDateOnly =
	                            String(d.getDate()).padStart(2, "0") + "-" +
	                            String(d.getMonth() + 1).padStart(2, "0") + "-" +
	                            d.getFullYear();
	                    }
	                }


	                content += "<td style='text-align:center'>" + poDateOnly + "</td>";


	                //content += "<td style='text-align:center'>" + result[j].PODATE + "</td>";
	                //content += "<td><input type='hidden' id='dstrbtrId" + j + "' value='" + result[j].DRUG_TYPE_ID + "' /></td>";
	                content += "<td style='text-align:center'>" + result[j].DSTRBTRNAME + "</td>";
	                content += "<input type='hidden' id='poId1_" + j + "' value='" + result[j].PO_ID + "'>";
					content += "<input type='hidden' id='mnfctrId_" + j + "' value='" + result[j].MNFCTR_ID + "'>";
					content += "<input type='hidden' id='mnfctrname_" + j + "' value='" + result[j].MNFCTRNAME + "'>";
					content += "<input type='hidden' id='itemId_" + j + "' value='" + result[j].ITEMID + "'>";
					content += "<input type='hidden' id='dstrbtrId_" + j + "' value='" + result[j].DSTRBTR_ID + "'>";
					content += "<td style='text-align:center;' id='drugType_" + j + "' >" + result[j].DRUGTYPE + "</td>";
	                content += "<td style='display:none;' id='drugCode_" + j + "'>" + result[j].DRUGCODE + "</td>";
	                content += "<td style='display:none;' id='indentId_" + j + "'>" + result[j].INDENT_ID + "</td>";
	                content += "<td style='text-align:center'>" + result[j].DRUGNAME + "</td>";
	                content += "<input type='hidden' id='drugId_" + j + "' value='" + result[j].DRUG_ID + "'>";
	                content += "<input type='hidden' id='drugTypeId_" + j + "' value='" + result[j].DRUG_TYPE_ID + "'>";
	                content += "<input type='hidden' id='submittedQty_" + j + "' value='" +
	                (result[j].ISSUE_QUANT || 0) + "'>";

	              
	                content += "<td style='text-align:center'>" + result[j].LVL + "</td>";
	                
	                content += "<td style='text-align:center'>" + result[j].RCP + "</td>";
	                content += "<td><input type='text' id='drugBatchNo_" + j + "' maxlength='50' class='form-control' style='font-size:13px; text-transform:uppercase;width:11em;' oninput=\"this.value=this.value.replace(/[^a-zA-Z0-9]/g,'').toUpperCase();\"/></td>";
	                /* content += "<td title='Invoice Date'><input type='text' id='invoiceDate_" + j + 
	                "' class='form-control invoiceDate_' style='width:8em;' value='" + todayStr + "'/></td>";
	                 */
	                 content += "<td title='Invoice Date'><input type='text' id='invoiceDate_" + j + "' class='form-control invoiceDate_' style='width:8em;'/></td>";

	                /* content += "<td title='Invoice Date'><input type='text' id='invoiceDate_" + j + "' class='form-control invoiceDate_' style='width:8em;'/></td>"; */
	                /* content += "<td><input type='text' id='invoiceNumber_" + j + "' maxlength='10' class='form-control' style='font-size:13px;text-transform:uppercase;width:10em;' oninput=\"this.value=this.value.replace(/[^a-zA-Z0-9]/g,'').toUpperCase();\"/></td>"; */
	               content += "<td><input type='text' id='invoiceNumber_" + j + "' maxlength='50' " +
		           "class='form-control invoiceNumber' style='font-size:13px;text-transform:uppercase;width:10em;' " +
		           "oninput=\"this.value=this.value.replace(/[^a-zA-Z0-9]/g,'').toUpperCase(); updateInvoice(this);\" /></td>";

	                content += "<td title='Expiry Date'><input type='text' id='drugexpiryDate_" + j + "' class='form-control drugExpiryDate' style='width:8em;'/></td>";
	             
	                content += "<td><input type='text' id='dispDrugQuantity_" + j + "' class='form-control' " +
	                "style='font-size:13px;width:8em;' " +
	                (status === 'CD1420'
	                    ? "value='" + result[j].ISSUE_QUANT + "' readonly "
	                    : "oninput=\"this.value=this.value.replace(/[^0-9]/g,''); calculateInvoiceAmount(" + j + "," + result[j].RCP + ");\" ") +
	                "/></td>";

	                
			         if (status === 'CD1420') {
			             content += "<td><input type='text' id='pendingQty_" + j + "' class='form-control' " +
			                        "style='font-size:13px;width:8em;' " +
			                        "oninput=\"this.value=this.value.replace(/[^0-9]/g,'').replace(/^0+/,''); " +
			                        "calculateInvoiceAmount(" + j + "," + result[j].RCP + "); \" /></td>";
			         }

	                content += "<td style='text-align:center;'>"
	                         + "<select id='gstSlab_" + j + "' class='form-control' style='font-size:13px;width:8em;'"
	                         + " onchange='calculateInvoiceAmount(" + j + "," + result[j].RCP + ");'>"
	                         + "<option value=''>--Select--</option>"
	                         + "<option value='0'>0%</option>"
	                         + "<option value='5'>5%</option>"
	                         + "<option value='12'>12%</option>"
	                         + "<option value='18'>18%</option>"
	                         + "</select></td>";

	                content += "<td><input type='text' id='invoiceAmount_" + j + "' maxlength='10' class='form-control' style='font-size:13px;width:9em;' readonly/></td>";
	                content += "<td><input type='text' id='gstAmount_" + j + "' maxlength='10' class='form-control' style='font-size:13px;width:9em;' readonly/></td>";
	                content += "<td><input type='text' id='poAmount_" + j + "' class='form-control' style='font-size:13px;width:9em;' readonly/></td>";
	                /* content += "<td><input type='file' id='invoiceDocument_" + j + "' accept='.pdf,.jpg,.png' class='form-control' style='font-size:13px;width:20em;'/></td>"; */

	                content += "</tr>";
	            }


	            document.getElementById("tbodyC1").innerHTML = content;
	            
	            var today = new Date();
	            today.setHours(0, 0, 0, 0); 
	            minExpiryDate = new Date(today);
	            minExpiryDate.setDate(minExpiryDate.getDate() + 90);
	            
	            $(".drugExpiryDate").datepicker({
	                defaultDate: "+1w",
	                changeMonth: true,
	                changeYear: true,
	                <%-- showOn: "both",
	                buttonImage: "<%=request.getContextPath()%>/images/calend.gif",
	                buttonImageOnly: true,
	                buttonText: "Calendar", --%>
	                minDate: minExpiryDate,
	                maxDate: "+5Y",
	                dateFormat: "dd-mm-yy",
	                /* onClose: function( selectedDate ) {
		    				$( "#toDate" ).datepicker( "option", "minDate", selectedDate );
		    			} */
	            });
	           

	            
	            $("[id^='invoiceDate_']").datepicker({
	                defaultDate: "+1w",
	                changeMonth: true,
	                changeYear: true,
	             <%--    showOn: "both",
	                buttonImage: "<%=request.getContextPath()%>/images/calend.gif",
	                buttonImageOnly: true,
	                buttonText: "Calendar", --%>  
	                minDate: "-5Y",
	               // minDate: 0,
	                maxDate: 0,
	                dateFormat: "dd-mm-yy"
	            });
	            $('html, body').animate({ scrollTop: 0 }, 500, 'linear');
	            $("#phcDataDiv").hide();
	            $("#phcBackBtn").hide();
	            $("#phcHeading").hide();
	            $("#phcCountDiv").show();     
	            $("#teamDtlsTbl").show();    
	            $("#submitBtn").show();
	            $("#statusHidden").remove();
	            $("body").append("<input type='hidden' id='statusHidden' value='" + status + "'>");
	            fn_hideImage();
	        }
	    });
	}
	function anyRowSelected() {
	    return $(".selectableCheckbox:not(#checkAll)").is(":checked");
	}

	
	function updateInvoice(input) {
	    GLOBAL_INVOICE_NO = input.value.trim();

	    $(".selectableCheckbox:not(#checkAll)").each(function () {
	        if (this.checked) {
	            $(this).closest("tr")
	                   .find("input[id^='invoiceNumber_']")
	                   .val(GLOBAL_INVOICE_NO);
	        }
	    });
	}

	$(document).on("change", ".selectableCheckbox", function () {

	    if (this.id === "checkAll") return;

	    var row = $(this).closest("tr");
	    var invoiceNoInput   = row.find("input[id^='invoiceNumber_']");
	    //var invoiceDateInput = row.find("input[id^='invoiceDate_']");

	    if (this.checked) {

	        // invoice number
	        if (GLOBAL_INVOICE_NO) {
	            invoiceNoInput.val(GLOBAL_INVOICE_NO);
	        }

	        // invoice date (same behaviour)
	       /*  if (!GLOBAL_INVOICE_DTE) {
	            GLOBAL_INVOICE_DTE = getTodayDate();
	        }
	        invoiceDateInput.val(GLOBAL_INVOICE_DTE);
 */
	    } else {
	        invoiceNoInput.val("");
	        //invoiceDateInput.val("");
	    }

	    if (!anyRowSelected()) {
	        GLOBAL_INVOICE_NO = "";
	       // GLOBAL_INVOICE_DTE = "";
	        $(".invoiceNumber").val("");
	        //$(".invoiceDate_").val("");
	    }
	});



	function handlePoSelection() {
	    var poNo = document.getElementById("poDropdown").value;
	    var status = document.getElementById("status").value;
	    
	    $("#submitBtn").hide();
	    $("#tbodyC1").empty();
	    $("#teamDtlsTbl").hide();
	    resetDrugDropdown(); 

	    if (poNo === "-1") {
	        alert("Please select a PO number.");
	        return;
	    }
	    if (status === "-1") {
	        alert("Please select a status.");
	        return;
	    }
	    fn_loadImage();
	    poRpt(poNo, status);
	    poRpt1(poNo, status,"");
	}

	function fn_checkAll() {
	    var elements = document.getElementsByClassName("selectableCheckbox");

	   /*  if ($("#checkAll").prop("checked")) {
	        if (!GLOBAL_INVOICE_DTE) {
	            GLOBAL_INVOICE_DTE = getTodayDate();
	        }
	    }
 */
	    for (var i = 1; i < elements.length; i++) {

	        var row = $(elements[i]).closest("tr");
	        var invoiceNoInput   = row.find("input[id^='invoiceNumber_']");
	       // var invoiceDateInput = row.find("input[id^='invoiceDate_']");

	        if ($("#checkAll").prop("checked")) {
	            elements[i].checked = true;

	            if (GLOBAL_INVOICE_NO) {
	                invoiceNoInput.val(GLOBAL_INVOICE_NO);
	            }
	            //invoiceDateInput.val(GLOBAL_INVOICE_DTE);

	        } else {
	            elements[i].checked = false;
	            invoiceNoInput.val("");
	            //invoiceDateInput.val("");
	        }
	    }

	    if (!$("#checkAll").prop("checked")) {
	        GLOBAL_INVOICE_NO = "";
	        //GLOBAL_INVOICE_DTE = "";
	    }
	}

	
	function calculateInvoiceAmount(index, rcp) {

	    const status = document.getElementById("statusHidden").value;
	    const gst = parseFloat(document.getElementById("gstSlab_" + index).value) || 0;

	    let qty = 0;
	    if (status === 'CD1420') {
	        const pendingQtyEl = document.getElementById("pendingQty_" + index);
	        qty = pendingQtyEl ? parseFloat(pendingQtyEl.value) || 0 : 0;
	    }
	    else {
	        qty = parseFloat(document.getElementById("dispDrugQuantity_" + index).value) || 0;
	    }

	    let baseAmount = rcp * qty;

	    document.getElementById("invoiceAmount_" + index).value = baseAmount.toFixed(2);
	    let gstAmount = 0;
	    let poAmount = baseAmount;
	    

	    if (gst > 0) {
	         gstAmount = (baseAmount * gst) / 100;
	         poAmount = baseAmount + gstAmount;
	        //document.getElementById("poAmount_" + index).value = poAmount.toFixed(2);
	    } 
	    document.getElementById("gstAmount_" + index).value = gstAmount.toFixed(2);
	    
	    document.getElementById("poAmount_" + index).value = poAmount.toFixed(2);
	}

	
	function fn_submit() {
		
		/* var status = $("#statusHidden").val(); 

	    if (status === 'CD1420') {
	        alert("Let store enter received quantity then vendor can submit remaining quantity");
	        return;
	    } */
		
	    var rows = $("#tbodyC1 tr");
	    if (rows.length === 0) {
	        alert("No records available to submit.");
	        return;
	    }
	    var wc = $("#dispname").val();
	    var vendorPOList = [];
	    var isValid = true;

	    rows.each(function(index) {
	        var row = $(this);
	        var isChecked = row.find("input[type='checkbox']").prop("checked");

	        if (!isChecked) return;

	        var poNo = row.find("td:eq(2)").text().trim();
	        var poDate = row.find("td:eq(3)").text().trim();
	        var mnfctrname = $("#mnfctrname_" + index).val().trim();
	        var indentId = $("#indentId_" + index).text().trim();
	        var drugType = $("#drugType_" + index).text().trim();
	        var drugName = row.find("td:eq(8)").text().trim();
	        var poQty = row.find("td:eq(9)").text().trim();
	        //var poStatus = row.find("td:eq(10)").text().trim();
	        var rcPrice = row.find("td:eq(10)").text().trim();
	        var drugId      = $("#drugId_" + index).val()?.trim();
	        var drugTypeId  = $("#drugTypeId_" + index).val()?.trim();
	        var mnfctrId    = $("#mnfctrId_" + index).val()?.trim();
	        var poId    = $("#poId1_" + index).val()?.trim();
	        var dstrbtrId   = $("#dstrbtrId_" + index).val()?.trim();
	        var batchNo = $("#drugBatchNo_" + index).val()?.trim();
	        var itemId = $("#itemId_" + index).val()?.trim(); 
	        var expiryDate = $("#drugexpiryDate_" + index).val()?.trim();
	        var invoiceNo = $("#invoiceNumber_" + index).val()?.trim();
	        var invoiceDate = $("#invoiceDate_" + index).val()?.trim();
	        var quantity = $("#dispDrugQuantity_" + index).val()?.trim();
	        var submittedQty = parseInt($("#submittedQty_" + index).val() || "0", 10);
	        var pendingQty = 0;
	       
	        if ($("#pendingQty_" + index).length) {
	            pendingQty = parseInt($("#pendingQty_" + index).val() || "0", 10);
	        }
	        
	        var isPartialPO = ($("#pendingQty_" + index).length > 0); 


	        var poQtyNum = parseInt(poQty || "0", 10);
	        if (submittedQty + pendingQty > poQtyNum) {
	            /* alert(
	                "Pending quantity exceeds allowed limit.\n\n" +
	                "PO Qty        : " + poQtyNum + "\n" +
	                "Already Given : " + submittedQty + "\n" +
	                "Allowed Now   : " + (poQtyNum - submittedQty)
	            ); */
	            alert("Pending quantity exceeds allowed limit");
	            isValid = false;
	            return false;
	        }

	        if (Number(quantity) > Number(poQty)) {
	            alert("Dispensed Quantity cannot be greater than PO Quantity in row " + (index + 1));
	            isValid = false;
	            return false;
	        }
	        var gstSlab = $("#gstSlab_" + index).val()?.trim();
	        var invoiceAmount = $("#invoiceAmount_" + index).val()?.trim();
	        
	        $("#hiddenIndentNo").val(indentId);
		    //$("#hiddenStatus").val(poStatus);

	        if (!batchNo || !expiryDate || !invoiceNo || !invoiceDate || !quantity || !gstSlab || !invoiceAmount ||
	        		 (isPartialPO && (!pendingQty && pendingQty !== 0))) {
	            alert("Please fill all required fields for row " + (index + 1));
	            isValid = false;
	            return false; 
	        }
	        var dateRegex = /^\d{2}-\d{2}-\d{4}$/;
	        var expParts = expiryDate.split("-");
	        var enteredExpiryDate = new Date(
	            parseInt(expParts[2], 10),   
	            parseInt(expParts[1], 10) - 1, 
	            parseInt(expParts[0], 10)    
	        );
	        enteredExpiryDate.setHours(0, 0, 0, 0);

	        if (enteredExpiryDate.getTime() < minExpiryDate.getTime()) {
	            alert(
	                "Expiry Date must be at least 90 days from today.\n" +
	                "Please correct Expiry Date in row " + (index + 1)
	            );
	            $("#drugexpiryDate_" + index).val(""); 
	            isValid = false;
	            return false;
	        }
	        if (!dateRegex.test(expiryDate)) {
	            alert("Expiry Date must be in format DD-MM-YYYY (Row " + (index + 1) + ")");
	            $("#drugexpiryDate_" + index).val(""); 
	            isValid = false;
	            return false;
	        }
	        if (!dateRegex.test(invoiceDate)) {
	            alert("Invoice Date must be in format DD-MM-YYYY (Row " + (index + 1) + ")");
	            $("#invoiceDate_" + index).val(""); 
	            isValid = false;
	            return false;
	        }
	    
	        var invParts = invoiceDate.split("-");
	        /* var enteredInvoiceDate = new Date(
	            parseInt(invParts[2], 10),     
	            parseInt(invParts[1], 10) - 1, 
	            parseInt(invParts[0], 10)      
	        );
	        enteredInvoiceDate.setHours(0, 0, 0, 0);

	        var today = new Date();
	        today.setHours(0, 0, 0, 0);

	        if (enteredInvoiceDate.getTime() !== today.getTime()) {
	            alert("Invoice Date must be today's date (Row " + (index + 1) + ")");
	            $("#invoiceDate_" + index).val("").focus(); 
	            isValid = false;
	            return false;
	        } */

	   
	        vendorPOList.push({
	            poNo: poNo,
	            poDate: poDate,
	            mnfctrname:mnfctrname,
	            indentId: indentId,
	            drugName: drugName,
	            drugType: drugType,
	            poQty: poQty,
	           // poStatus: poStatus,
	            rcPrice: rcPrice,
	            batchNo: batchNo,
	            expiryDate: expiryDate,
	            invoiceNo: invoiceNo,
	            itemId: itemId,
	            invoiceDate: invoiceDate,
	           // quantity: quantity,
	            quantity: quantity.toString(),  
    			pendingQty: pendingQty.toString(),
	            gstSlab: gstSlab,
	            invoiceAmount: invoiceAmount,
	            drugId: drugId,
	            drugTypeId: drugTypeId,
	            mnfctrId: mnfctrId,
	            dstrbtrId: dstrbtrId,
	            poId: poId
	        });
	    });

	    if (!isValid) return;
	    if (vendorPOList.length === 0) {
	        alert("Please select at least one record before submitting.");
	        return;
	    }
	    
	    if (!confirm("Do you want to submit ?")) {
	        return; 
	    }

	    var formData = new FormData();
	    formData.append("vendorPOList", JSON.stringify(vendorPOList));
	   // console.log("vendorPOList:::", JSON.stringify(vendorPOList));
	    formData.append("dispname",wc);
	    var selectedItemIds = vendorPOList.map(function(item) {
	        return item.itemId;
	    });
	    $("#hiddenItemIds").val(selectedItemIds.join(","));
	    $("#hiddenPoNo").val(vendorPOList[0].poNo);

	    $.ajax({
	        url: "vendorActionNew.do?actionFlag=saveInventoryDetailsVendor",
	        type: "POST",
	        data: formData,
	       /*   data: {
       			 vendorPOList: JSON.stringify(vendorPOList),
       			 dispname: wc
    			}, */
	        processData: false,
	        contentType: false,       
	       
	        success: function(response) {
	        	/* if (response === "STORE_PENDING") {
	                alert("Please wait. Store has not completed the previous submission.");
	                return;
	            } */
	            alert("Inventory details submitted successfully!");
	            fn_vendorPrintForm();
	            $("#tbodyC1").empty();
	            $("#teamDtlsTbl").hide();
	            $("#phcCountDiv").hide();
	            $("#submitBtn").hide();

	          
	            $("#dispname").val("-1");   
	            $("#status").val("-1");     
	            $("#poDropdown").val("-1"); 
	            resetDrugDropdown();
	            //$("#drugListDropdown").val("-1"); 
	           
	        },
	        error: function(xhr, status, error) {
	            alert("Error while saving data: " + error);
	        }
	    });
	}
	function ajax_download(url, data, input_name) {
		 $('#download_iframe').remove();
	    var $iframe,
	        iframe_doc,
	        iframe_html;

	    if (($iframe = $('#download_iframe')).length === 0) {
	        $iframe = $("<iframe id='download_iframe'" +
	                    " style='display: none' src='about:blank'></iframe>"
	                   ).appendTo("body");
	    }

	    iframe_doc = $iframe[0].contentWindow || $iframe[0].contentDocument;
	    if (iframe_doc.document) {
	        iframe_doc = iframe_doc.document;
	    }

	    iframe_html = "<html><head></head><body><form method='POST' action='" +
	                  url +"'>" +
	                  "<input type=hidden name='" + input_name + "' value='" +
	                  JSON.stringify(data) +"'/></form>" +
	                  "</body></html>";

	    iframe_doc.open();
	    iframe_doc.write(iframe_html);
	    $(iframe_doc).find('form').submit();
	}
	function fn_vendorPrintForm() {
		var wc = $("#dispname").val();
		 var poNo = $("#hiddenPoNo").val();
	    //var poNo = $("#poDropdown").val();
	    var itemIds = $("#hiddenItemIds").val();
	     
	    var url = "vendorActionNew.do?actionFlag=vendorPdf"+"&wc=" + wc + "&poNo=" + poNo+ "&itemIds=" + itemIds;
	   
	    ajax_download(url, {}, 'dataname');
	    
	}



</script>
</body>

</html>