<%
/**
 * FILENAME     :viewTdLabInvestigations.jsp
 * @AUTHOR      : Sai Krishna	
 * --------------------------------------------------------------
 * Change Id       AUTHOR          DESCRIPTION
 * ---------------------------------------------------------------
 *  8134		 Sai Krishna    Jsp to view the Reports generated by Td
 *    
 * --------------------------------------------------------------
 **/
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" import="java.util.ArrayList,
                              java.util.Iterator,
                              java.util.List,com.ahct.patient.vo.PatientVO" %>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
     <%@ taglib uri="/WEB-INF/tld/struts-html.tld" prefix="html"%>
     <%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
     <%@ taglib uri="/WEB-INF/tld/struts-logic.tld" prefix="logic"%>
     <%@ taglib uri="/WEB-INF/tld/struts-bean.tld" prefix="bean"%>
     
     <%@ include file="/common/include.jsp"%>
     <%@ page import="com.ahct.patient.vo.PatientVO" %>
     <%@ page import="java.text.SimpleDateFormat" %>
     <%@ page import="java.util.Date" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
     
     

<fmt:setLocale  value='<%=session.getAttribute("LangID")%>' />
<fmt:bundle basename="Registration">

<html>

<style> #ui-id-4{ width:15%; }#ui-id-6,#ui-id-3,#ui-id-1,#ui-id-2,#ui-id-5 { width:35%; }
.custom-combobox-input {    margin: 0;    padding: 0.3em; background:#fff;border:1px solid #e6e6e6; }
body{font-size:1.2em !important;}
</style>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title ><fmt:message key="EHF.Title.PatientRegistration"/></title>
<LINK href="css/patient.css" type="text/css" rel="stylesheet">
<link href="css/themes/<%=themeColour%>/commonEhfCss.css" rel="stylesheet" type="text/css" media="screen">
<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css">
<script src="js/jquery-3.6.4.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="bootstrap/js/bootbox.min.js"></script>
<%@ include file="/common/includeCalendar.jsp"%>  
<script src="js/jquery.msgBox.js" type="text/javascript"></script>
<script type="text/javascript" src="js/patientscripts.js"></script>
<script src="bootstrap/js/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="bootstrap/css/datepicker3.css">


<style>
input:disabled, select:disabled{
background-color:#ddd;
}
.loading #loadbg {
    display: block;
    background-color: rgba(0, 0, 0, 0.5);
    color: white;
    font-size: 18px;
    text-align: center;
    padding: 20px;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    border-radius: 8px;
    z-index: 1000;
}
 .radio-group-container {
        display: flex;
        justify-content: center;
        padding: 15px 0;
        background-color: #f9f9f9;
        border-bottom: 1px solid #ccc;
    }

    .radio-group-container label {
        margin: 0 15px;
        font-weight: bold;
        font-size: 15px;
        cursor: pointer;
    }

    .radio-group-container input[type="radio"] {
        margin-right: 5px;
    }

    /* Optional: Add hover and selected styling */
    .radio-group-container input[type="radio"]:hover + span,
    .radio-group-container input[type="radio"]:checked + span {
        color: #007bff;
    }
    
    
     #remarksSection {
        text-align: center;
        margin-top: 20px;
    }

    #remarksSection textarea {
        width: 1200px;
        height: 100px;
        margin-bottom: 10px;
        resize: none;
    }

    #remarksSection button {
        padding: 6px 12px;
        font-size: 14px;
        cursor: pointer;
    }
    
  .form-row {
    display: flex;
    gap: 20px;
    margin: 15px;
  }

  .form-group {
    display: flex;
    flex-direction: column;
  }

  .form-group label {
    margin-bottom: 4px;
    font-weight: normal;
  }

  input[type="text"], textarea {
    padding: -11px;
    border: 1px solid #ccc;
    border-radius: 4px;
  }

  textarea {
    width: 393px;
    height: 100px;
    resize: none;
  }

          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 0.6;
            color: #333;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f9fc;
        }
        
        h1 {
            color: #2c3e50;
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        
        .note-date {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 15px;
            overflow: hidden;
        }
        
        .date-header {
            background-color: #6aa9d3;;
            color: white;
            padding: 12px 15px;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-weight: bold;
        }
        
        .date-header:hover {
            background-color: #2980b9;
        }
        
        .date-header::after {
            content: '+';
            font-size: 20px;
            transition: transform 0.3s;
        }
        
        .date-header.active::after {
            content: '-';
        }
        .note-content {
            padding: 0;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out, padding 0.3s ease;
        }
        
        .note-content.active {
            padding: 15px;
            max-height: 1000px;
        }
        
        .note-section {
            margin-bottom: 15px;
            padding-bottom: 15px;
            border-bottom: 1px solid #eee;
        }
        
        .note-section:last-child {
            border-bottom: none;
            margin-bottom: 0;
            padding-bottom: 0;
        }
        
        .note-title {
            color: #3498db;
            margin-top: 0;
            margin-bottom: 10px;
            font-size: 18px;
        }
        
        .note-text {
            margin: 0;
            white-space: pre-line;
        }
        
        .no-notes {
            text-align: center;
            color: #7f8c8d;
            font-style: italic;
            padding: 20px;
        }
        .tbcellCss {
		    margin: 2px;
		    padding: 7px;
		    background: #f8f8f8;
		    border: 1px solid #e6e6e6;
		}
			
	 .flex-container {
	    display: flex;
	    gap: 20px; /* space between the two blocks */
	    align-items: flex-start;
	    flex-wrap: wrap; /* optional if you want it responsive */
	}
	
	.note-item {
	    min-width: 120px; /* optional */
	}
	 table {
        width: 100%;
        table-layout: auto;
        border-collapse: collapse;
    }
    td,t{
    padding:7px;
    }       
</style>

<script type="text/javascript">
//sowmya
function fn_loading(){
	document.getElementById('loadid').innerHTML="<div id='loadbg'>Loading...</div>";
	document.getElementById("loadid").className="loading";
}
function fn_removeLoading(){
	document.getElementById("loadid").className="";
	document.getElementById('loadid').innerHTML="<div id=''>";
}
 function fn_backDrug() {
	 parent.fn_viewTdInvstRegPtLst();
} 	
</script>
</head>
<body>

<form method="post">

<div class="load" id="loadid"></div>
	<logic:notEmpty name="patientForm" property="msg">
	    <script language="javascript" type="text/javascript">
	    bootbox.alert('<bean:write name="patientForm" property="msg"/>');
	    </script>
	</logic:notEmpty>
  
<div>
<br>


<table class="tbheader">
  <tr><td align="Center" style="padding-top: 0%;"><b style="font-size: 14px;">PATIENT INFORMATION</b></td></tr>
</table>
<br>
<table>
  <tr><td  width="10%" class="labelheading1 tbcellCss" ><b>Registration Number</b>
   <td id="patNo" width="25%" class="tbcellBorder">
    <b>&nbsp;<bean:write name="patientForm" property="patientNo"/></b>
  </td>
      <td width="2%">&nbsp;</td>
      <td  width="25%" class="labelheading1 tbcellCss" ><b>Card Number</b></td><td id="cardNo" width="25%" class="tbcellBorder"><b> &nbsp;<bean:write name="patientForm" property="cardNo"/></b></td>
  </tr>
	<tr>	
		<td class="labelheading1 tbcellCss" width="25%"><b>Name</b></td><td class="tbcellBorder" width="25%"><b>&nbsp;<bean:write name="patientForm" property="fname" /></b></td>
	   <td width="2%">&nbsp;</td> 
	   <td class="labelheading1 tbcellCss" width="25%"><b>Date and Time Of Admission</b></td><td class="tbcellBorder" width="25%"><b>&nbsp;<bean:write name="patientForm" property="dateOfBirth"/></b></td>
	</tr>

	<tr>
		 <td class="labelheading1 tbcellCss" width="25%"><b>Gender</b></td><td class="tbcellBorder" width="25%"><b>&nbsp;<bean:write name="patientForm" property="gender"/></b></td>
		<!--  <td width="2%">&nbsp;</td> -->
	</tr>
	<tr>
	  <td class="labelheading1 tbcellCss" width="25%"><b>Age</b></td><td class="tbcellBorder" width="25%"><b>&nbsp;<bean:write name="patientForm" property="years"/></b></td>
	  	 <td width="2%">&nbsp;</td> 
	</tr>
 </table>
<br>
  <div id="medicineHistorySection">
    <table class="tbheader">
      <tr>
        <td align="Center" style="padding-top: 0%;"><b style="font-size: 14px;">LAB ORDER</b></td>
      </tr>
    </table>

    <table id="drugsTablePast" class="table table-bordered" style="width: 100%; margin-top: 20px;">
      <thead>
        <tr>
          <th width="10%" class="labelheading1 tbcellCss existDrugs">S.No</th>
          <th width="22%" class="labelheading1 tbcellCss existDrugs">Order Id</th>
          <th width="22%" class="labelheading1 tbcellCss existDrugs">Investigation Name</th>
          <!-- <th width="12%" class="labelheading1 tbcellCss existDrugs">PatientId</th> -->
           <th width="23%" class="labelheading1 tbcellCss existDrugs">Date and Time</th>
           <th width="23%" class="labelheading1 tbcellCss existDrugs">Action</th>
        </tr>
      </thead>
      <tbody>
        <c:set var="serial" value="1"/>
        <c:forEach var="drug" items="${labDetails}">
            <tr>
              <td class="tbcellBorder"><strong>${serial}</strong></td>
              <td class="tbcellBorder"><strong>${drug.swBorders}</strong></td>
              <td class="tbcellBorder"><strong>${drug.TYPE3}</strong></td>
              <td class="tbcellBorder"><strong>${drug.caseRegDate}</strong></td>
             <%--  <td>${drug.patientId}</td> --%>
              <td>
                <button class="btn btn-primary btn-sm" onclick="javascript:sendReportRequest('${drug.cardNo}','${drug.swBorders}'); return false;">View Report</button>
              </td>
            </tr>
            <c:set var="serial" value="${serial + 1}" />
        </c:forEach>
      </tbody>
    </table>
  </div>
 <script>
	function sendReportRequest(benId, patId) {
		console.log("sendReportRequest called with:", benId, patId);
		fn_loading();
	    var xhr2 = new XMLHttpRequest();
	    xhr2.open("POST", "https://tdmobile.bhishak.net/api/Reports/GetReport", true);
	    xhr2.setRequestHeader("Content-Type", "application/json");
	    xhr2.onreadystatechange = function () {
	        if (xhr2.readyState === 4) {
	            fn_removeLoading();
	            if (xhr2.status === 200) {
	                try {
	                    if (!xhr2.responseText.trim()) {
	                        alert("Empty response from server");
	                        return;
	                    }
	                    var data = JSON.parse(xhr2.responseText);
	                    if (data.success) {
	                        console.log("Response:: "+data.response);
	                    	openPopup(data.response);
	                    } else {
	                        alert("Report not generated.");
	                    }
	                } catch (error) {
	                    console.error("Error parsing JSON:", error);
	                }
	            } else {
	                console.error("HTTP Error:", xhr2.status);
	            }
	        }
	    };
	    var requestData = JSON.stringify({
	    	 hpPatientId: benId,
	        hpVisitId: patId
	    });
	    console.log("Request Data:", requestData);
	    xhr2.send(requestData);
	}
  function openPopup(reportUrl) {
	    if (reportUrl) {
	        window.open(reportUrl,"Reports",'width=850,height=900,resizable=yes,top=150,left=200,toolbar=no,minimize=no,status=no,memubar=no,location=no,scrollbars=yes');
	    } else {
	        alert("Invalid report URL");
	    }
	}
  </script>
<%
    // Attempt to retrieve the registeredPatientInvstList directly from the request attribute
    Object registeredPatientInvstListObj = request.getAttribute("registeredPatientInvstList");

    // Check if it exists and is not empty
    boolean hasRegisteredPatientInvst = false;
    if (registeredPatientInvstListObj instanceof java.util.List) {
        java.util.List<?> registeredPatientInvstList = (java.util.List<?>) registeredPatientInvstListObj;
        hasRegisteredPatientInvst = !registeredPatientInvstList.isEmpty();
    }
%>

<%
    // Attempt to retrieve the registeredPatientInvstList directly from the request attribute
    Object registeredPatientsListObj = request.getAttribute("registeredPatientsList");

    // Check if it exists and is not empty
     boolean hasRegisteredPatientList = false;
    if (registeredPatientsListObj instanceof java.util.List) {
        java.util.List<?> registeredPatientsList = (java.util.List<?>) registeredPatientsListObj;
        hasRegisteredPatientList = !registeredPatientsList.isEmpty(); 
    } 
%>
<div style="text-align: center;">
  <button type="button"class="btn btn-primary" onclick="fn_backDrug()">Back</button>
</div>
<br/>
</form>
</body>
</html>

</fmt:bundle>